DROP FUNCTION IF EXISTS move_escrowed_funds(UUID, UUID, TEXT);
DROP FUNCTION IF EXISTS unescrow_funds(UUID);
DROP FUNCTION IF EXISTS escrow_funds(UUID, NUMERIC);
DROP FUNCTION IF EXISTS move_locked_funds(UUID, UUID, NUMERIC, TEXT);
DROP FUNCTION IF EXISTS unlock_funds(UUID, NUMERIC);
DROP FUNCTION IF EXISTS lock_funds(UUID, NUMERIC);
DROP FUNCTION IF EXISTS burn_funds(UUID, NUMERIC);
DROP FUNCTION IF EXISTS mint_funds(UUID, NUMERIC);
